
const sceneTitles = ["camoufleur", "murdabad", "determent", "divisor", "unfuddled", "frankfurter", "ladino", "reprotest", "fiendishness", "regressive", "unripened", "polemics", "kingmaking", "socialise", "shininess", "inrushing", "olomouc", "retreative", "marruecos", "chivaree", "elrica", "silvanus", "overture", "mortgagee", "overspend", "quilleted", "deriding", "uncloven", "ethicise", "sulfuric", "comanche", "nonsentient", "briolette", "saxony", "manminit", "cockiest", "lyriform", "zareba", "pinero", "limerick", "buildable", "severest", "chatelain", "highholder", "oxidise", "thriftlessness", "bawdiest", "brazilin", "bushranging", "rewedding", "platysmas", "zibelline", "irishized", "vivandi", "pachytene", "twelvepenny", "convincer", "evictee", "curbable", "rockfishes", "stoplessness", "schiavone", "gamekeeper", "dissuaded", "terzetto", "comales", "shovelboard", "misplacement", "preroyal", "seigniories", "loafishness", "bedeswomen", "dominion", "stonable", "gormandize", "quirinal", "tissuey", "presbyter", "nonenrolled", "squirrelly", "unchanging", "spikier", "ascendent", "lineal", "wigtownshire", "enmity", "dopatta", "unspiral", "funnier", "etherege", "mephisto", "harappan", "pupilless", "bologna", "promiseful", "parolee", "unsuited", "aspectant", "woefully", "dominus", "furibund", "notify", "cubism", "capelin", "atiptoe", "edgier", "flickery", "flabbiest", "disbudding", "goutiness", "durable", "methedrine", "passaic", "aerolite", "predisliked", "blushingly", "waterlike", "hyracoid", "ichnolite", "eulogized", "erasure", "snootily", "yaunde", "adabelle", "pesticide", "optimized", "gluttonous", "gravedigger", "willendorf", "leggiest", "fuzzier", "swindlingly", "zamenhof", "prothetic", "francophile", "lecythus", "caerphilly", "noncausal", "subscripture", "torero", "gaposis", "groundlessness", "nematic", "tubular", "littoral", "architraved", "transferrer", "nonbiting", "japanner", "enticing", "agulhas", "steeplejack", "patchiest", "outwearied", "refractive", "deviser", "gypseian", "eunuchoid", "menial", "diopter", "iliac", "zamindar", "synsacral", "candlelight", "alchemise", "tlaxcala", "sialoid", "unwakened", "librating", "cannulate", "regradate", "unsuiting", "praeneste", "malaga", "disrepute", "gamekeeping", "treasurer", "boastfully", "calcimine", "synchronism", "privity", "predispute", "cystotome", "nongestic", "changeover", "jackpiling", "gruelling", "franklinton", "exudate", "reembraced", "leatherwork", "nondeafened", "jackassness", "frostbiting", "resurrect", "perfumy", "drawable", "monstrance", "radom", "newscast", "formol", "mishear", "raddled", "mellow", "giblet", "thymi", "outstride", "hampshire", "pasting", "sadware", "houmous", "renounced", "insight", "graveclothes", "nookie", "broider", "vying", "enwomb", "hooknose", "silva", "nisi", "veneer", "defy", "redipt", "hofei", "affirm", "ungagged", "react", "se''nnight", "ralegh", "redhorse", "beryl", "bribing", "reedley", "welty", "chary", "fleeing", "reeving", "lotos", "strobile", "frogman", "tapley", "hoedown", "barnum", "beddoes", "claret", "model", "jetsam", "swellfish", "lequear", "tinsmith", "gaullist", "fungo", "duette", "aurochs", "rockford", "atum", "spenser", "extern", "frances", "hechsher", "baiae", "hitter", "jokeless", "haemon", "hailstone", "nighthawk", "cochise", "tonic", "dropper", "curtis", "bala", "camper", "inarm", "ending", "halfmoon", "gascogne", "boughten", "meanly", "douzepers", "coccoid", "munda", "sankhya", "tabby", "coaxer", "elie", "mullion", "pavan", "cancer", "storklike", "inversed", "kickboard", "smoking", "disprized", "unstitched", "grapestone", "pearsall", "szilard", "handwork", "benempt", "erlang", "febrile", "hogget", "piqu", "foreclosed", "sherrill", "wadna", "drastic", "budded", "briefing", "wheelwright", "crispi", "uprise", "inrush", "minim", "blackwood", "fuseless", "neumann", "bistro", "provoke", "drover", "reblown", "financed", "cheater", "flitted", "flameproof", "miching", "tasseled", "handcar", "simn", "hartford", "aircraft", "cosset", "squeegeed", "broody", "yearning", "humphrey", "celia", "henty", "sendoff", "siobhan", "decide", "bondman", "survive", "rayner", "zwingli", "schainbein", "tapeman", "learned", "flagrant", "prefreeze", "cohort", "foxtrot", "tientsin", "fausto", "regard", "mistal", "samson", "lansat", "glasgow", "threadless", "dolor", "venlo", "enroll", "charka", "sawney", "dukkha", "ube", "furphy", "eucrite", "powdove", "christophe", "bootless", "astral", "freon", "accompt", "qaddish", "xylene", "daybreak", "confute", "heathfowl", "haply", "corbeil", "tyndall", "dishful", "beadlike", "romberg", "knotlike", "phosphate", "mizen", "sandhi", "apples", "poitou", "hawkie", "spandex", "staunch", "emf", "musk", "fringe", "chinch", "drove", "week", "star", "grouse", "cts", "vexed", "frump", "schlepp", "breeks", "clart", "fikh", "dsm", "word", "rhet", "bland", "wmo", "exec", "ooze", "find", "dis", "schorl", "phies", "raf", "gear", "ling", "scouse", "grant", "ops", "sib", "yon", "nail", "byre", "vie", "lwm", "fowl", "teil", "spick", "crewe", "cyl", "should", "lall", "gilt", "plu", "toil", "neat", "cab", "team", "fesse", "macc", "stuffed", "loo", "plough", "bore", "slub", "wolfe", "spence", "dulse", "grutch", "duds", "rath", "yawp", "gale", "twixt", "sansk", "tripl", "sylph", "blunge", "dirl", "steel", "musth", "fight", "kneel", "ash", "gulf", "swish", "grid", "trank", "aune", "spleen", "cowl", "read", "dovap", "rtr", "near", "fug", "waif", "youth", "dodds", "range", "wad", "caw", "prec", "who", "made", "sought", "chuff", "dice", "whf", "stones", "share", "verne", "vives", "phaye", "pep", "three", "stan", "croute", "floc", "blair", "mask", "kench", "maj", "donne", "stipe", "slip", "ngwee", "fob", "whiff", "hyte", "thin", "spore", "peen", "spurge", "cryst", "spice", "aune", "emf", "whee", "y'all", "scrag", "unrra", "kale", "trout", "mit", "ufo", "sturt", "cronk", "lamb", "czech", "advt", "price", "geod", "schnook", "tongues", "blat", "klebs", "tay", "gulch", "muzz", "din", "rolph", "jimp", "huh", "nsw", "quarte", "switz", "rage", "mill", "quitch", "yod", "broke", "poove", "floyd", "spook", "swound", "sark", "swats", "maist", "fab", "mba", "calx", "strike", "irl", "tide", "gnar", "dsp", "woald", "ain't", "nasa", "green", "nib", "thorp", "ernst", "peeve", "brail", "wren", "huss", "spark", "ton", "fringe", "gross", "quart", "sphene", "receive", "trap", "imaginary", "structure", "pushy", "flavor", "use", "matter", "look", "cactus", "unlock", "grip", "abashed", "elfin", "war", "retire", "repulsive", "dusty", "devilish", "red", "greedy", "skip", "lively", "conscious", "huge", "freezing", "pink", "flow", "blot", "foot", "number", "equal", "curtain", "maniacal", "breath", "insect", "concentrate", "nauseating", "limping", "glossy", "laugh", "disapprove", "lie", "didactic", "rock", "uncovered", "channel", "way", "romantic", "abounding", "habitual", "tearful", "smell", "middle", "economic", "cracker", "mind", "drunk", "help", "fail", "songs", "periodic", "brother", "regular", "bottle", "scared", "wrathful", "groan", "teeny", "adventurous", "increase", "stone", "thread", "search", "believe", "little", "sisters", "snow", "admire", "badge", "brash", "mundane", "underwear", "suspect", "icky", "slow", "burst", "hospital", "passenger", "chivalrous", "wrap", "supreme", "recess", "flood", "abject", "turkey", "interest", "zesty", "mature", "twist", "swanky", "fancy", "unknown", "hour", "macabre", "joyous", "lighten", "youthful", "start", "itch", "spiritual", "volcano", "hate", "quilt", "abortive", "dashing", "demonic", "men", "delay", "team", "ignore", "wistful", "straight", "lumber", "trains", "drab", "nasty", "offer", "married", "thick", "coal", "dam", "destruction", "unkempt", "productive", "force", "mate", "strengthen", "dull", "pocket", "alert", "famous", "fabulous", "travel", "whine", "object", "corn", "fasten", "tawdry", "sincere", "attach", "level", "cultured", "shape", "blood", "pies", "axiomatic", "tumble", "balance", "cure", "achiever", "whispering", "exchange", "nosy", "continue", "walk", "scarf", "improve", "line", "stingy", "fair", "guitar", "release", "amuse", "imperfect", "yawn", "liquid", "educate", "coast", "jog", "utopian", "lyrical", "protect", "heavenly", "hammer", "limit", "muddle", "squirrel", "control", "winter", "deeply", "risk", "faulty", "interfere", "wriggle", "fade", "group", "squalid", "reading", "outrageous", "boundless", "afford", "high", "cats", "broad", "step", "tender", "careless", "earthquake", "squeak", "jar", "clean", "hum", "domineering", "sulky", "shock", "questionable", "tease", "unsightly", "inexpensive", "noxious", "obsolete", "tent", "memorise", "pleasure", "secret", "voyage", "hilarious", "admit", "impress", "coat", "square", "lock", "print", "thumb", "fireman", "unadvised", "weak", "dramatic", "billowy", "absent", "authority", "curved", "descriptive", "pan", "share", "repeat", "racial", "distance", "town", "far-flung", "bashful", "bent", "lovely", "breakable", "mass", "stream", "toy", "fly", "babies", "disgusted", "report", "ten", "cuddly", "scrub", "kettle", "voice", "abundant", "important", "blue-eyed", "late", "hug", "goofy", "pen", "own", "cause", "nappy", "versed", "dark", "intelligent", "chicken", "eager", "grateful", "dislike", "ruthless", "book", "flower", "unable", "yarn", "meal", "overjoyed", "wonderful", "zippy", "nod", "cherries", "blushing", "gusty", "basin", "activity", "doubt", "taste", "gaudy", "spiteful", "learned", "sweltering", "mark", "sense", "confess", "mice", "laborer", "stick", "pancake", "orange", "silly", "annoying", "spark", "tongue", "yoke", "smash", "blind", "furtive", "faint", "proud", "alarm", "wilderness", "minister", "chalk", "obnoxious", "miniature", "quarter", "soap", "dear", "rich", "ad hoc", "abstracted", "sick", "program", "load", "tightfisted", "jump", "downtown", "bone", "shivering", "grab", "level", "arch", "fine", "super", "mend", "kiss", "measure", "accessible", "poison", "well-to-do", "distribution", "spring", "humor", "quicksand", "deer", "girl", "quixotic", "marble", "polish", "hope", "club", "engine", "grass", "example", "bomb", "picayune", "advice", "eight", "brush", "fax", "list", "cover", "jazzy", "key", "bow", "jaded", "homely", "view", "obtain", "size", "meeting", "cobweb", "brake", "languid", "sticky", "ahead", "unit", "panicky", "magnificent", "quill", "wide-eyed", "current", "breathe", "present", "fresh", "female", "call", "soda", "wail", "brake", "shop", "irritating", "busy", "energetic", "sudden", "psychedelic", "next", "fearful", "evanescent", "sophisticated", "side", "scientific", "colossal", "cart", "parcel", "watch", "observant", "servant", "haircut", "meaty", "root", "rabid", "legal", "befitting", "nonstop", "hand", "volatile", "salt", "protest", "decay", "ants", "symptomatic", "boiling", "bizarre", "finger", "stocking", "whistle", "private", "pipe", "snakes", "talented", "historical", "brave", "live", "shiny", "gate", "thirsty", "greet", "rejoice", "laugh", "recognise", "ratty", "belligerent", "vest", "carpenter", "male", "grain", "surround", "tasteless", "stitch", "verse", "wander", "wide", "owe", "impolite", "juggle", "religion", "play", "strong", "weigh", "ducks", "exist", "afterthought", "pizzas", "careful", "pump", "drawer", "skillful", "gruesome", "lowly", "sneeze", "drink", "day", "dinner", "snatch", "produce", "grin", "bawdy", "ink", "massive", "bed", "noise", "terrify", "slip", "throat", "count", "same", "alive", "good", "knowing", "glamorous", "dizzy", "solid", "tank", "enjoy", "science", "panoramic", "flawless", "lettuce", "brainy", "plan", "bee", "picture", "waggish", "metal", "wet", "feeble", "crime", "jeans", "insidious", "rainstorm", "floor", "guide", "average", "toe", "kindhearted", "pie", "juice", "unequal", "range", "troubled", "trick", "sassy", "connection", "son", "yak", "wash", "bouncy", "window", "pedal", "ground", "match", "needy", "ball", "roll", "bubble", "loud", "file", "disastrous", "debonair", "messy", "snails", "responsible", "escape", "treatment", "industrious", "juvenile", "sturdy", "moan", "tiger", "aberrant", "lush", "base", "harmony", "rightful", "van", "violent", "ultra", "scorch", "dinosaurs", "hover", "flower", "mere", "scatter", "plants", "lazy", "suppose", "irate", "aloof", "end", "better", "decorate", "vagabond", "applaud", "reduce", "exuberant", "class", "chubby", "hard", "test", "unarmed", "recondite", "past", "expand", "ask", "black-and-white", "copper", "sail", "jellyfish", "cagey", "star", "fallacious", "crush", "invincible", "year", "brawny", "place", "nippy", "premium", "aspiring", "flat", "reason", "needless", "right", "spark", "enchanting", "gifted", "malicious", "reach", "march", "earsplitting", "shoes", "fold", "unusual", "lame", "office", "double", "lick", "alluring", "helpless", "deserve", "weary", "succeed", "unpack", "half", "listen", "flag", "shocking", "wash", "turn", "destroy", "pick", "profuse", "fold", "jagged", "prose", "peel", "insurance", "grade", "glow", "payment", "suit", "parched", "grouchy", "steadfast", "silent", "iron", "overflow", "vulgar", "minor", "uneven", "hurry", "depressed", "sofa", "attempt", "bewildered", "gamy", "lumpy", "subdued", "reign", "protective", "look", "interest", "bulb", "hook", "plant", "attractive", "remarkable", "oafish", "nifty", "earn", "zealous", "rest", "doctor", "paste", "beds", "hot", "different", "trade", "smelly", "remember", "frail", "decisive", "obese", "pale", "cheerful", "scissors", "dapper", "enthusiastic", "present", "ignorant", "reaction", "ruddy", "uttermost", "slave", "actually", "thankful", "jealous", "leather", "shaggy", "odd", "lunchroom", "smile", "craven", "slimy", "cattle", "need", "hall", "wry", "wakeful", "friendly", "tired", "parallel", "hobbies", "superficial", "synonymous", "volleyball", "spot", "drown", "pig", "spoon", "puny", "kneel", "glue", "store", "land", "incompetent", "cap", "press", "political", "disillusioned", "shiver", "zephyr", "wealth", "save", "waste", "handsome", "grubby", "aggressive", "direful", "neck", "condemned", "silver", "seemly", "standing", "wealthy", "giddy", "cream", "party", "argue", "influence", "condition", "exultant", "bolt", "direction", "acrid", "toes", "aboard", "train", "moaning", "shoe", "ear", "pollution", "tough", "caring", "overt", "confused", "instruct", "sin", "start", "wire", "carve", "eminent", "island", "drip", "poke", "luxuriant", "page", "adjoining", "clap", "scratch", "check", "cough", "imagine", "offbeat", "excite", "practise", "correct", "wonder", "crate", "clip", "machine", "reward", "camera", "eatable", "disturbed", "consist", "forgetful", "cows", "plane", "stage", "lackadaisical", "smooth", "head", "trees", "week", "roasted", "faithful", "attack", "joke", "rat", "hallowed", "rely", "nerve", "compare", "precede", "texture", "kiss", "thoughtful", "tooth", "dare", "one", "futuristic", "windy", "scale", "bushes", "skin", "beautiful", "grandmother", "exciting", "colour", "smash", "art", "boot", "shy", "happy", "hateful", "note", "sprout", "push", "tense", "reject", "annoyed", "mine", "splendid", "greasy", "sea", "flight", "park", "rain", "refuse", "steer", "sweet", "supply", "rail", "determined", "foamy", "shrug", "surprise", "tangible", "unite", "third", "meek", "camp", "spiffy", "worried", "cheat", "ordinary", "sordid", "abandoned", "acceptable", "buzz", "relax", "kaput", "scare", "oval", "yard", "record", "statuesque", "toothbrush", "teeth", "dust", "rhetorical", "letters", "fear", "heap", "scattered", "possible", "whistle", "yell", "fool", "existence", "shallow", "opposite", "thunder", "envious", "whimsical", "bloody", "hop", "vase", "simplistic", "muscle", "avoid", "bright", "attraction", "lucky", "adhesive", "frame", "vacation", "long-term", "secretive", "mindless", "delirious", "obey", "ubiquitous", "hanging", "disappear", "trail", "touch", "mighty", "rapid", "alert", "acoustic", "door", "sheep", "snail", "ladybug", "queue", "pricey", "alike", "road", "cheese", "fluffy", "man", "women", "dock", "smile", "sack", "groovy", "willing", "blink", "rush", "branch", "guard", "shelter", "puffy", "calculator", "warlike", "beef", "annoy", "calculate", "queen", "nonchalant", "open", "diligent", "guarantee", "snobbish", "discreet", "bit", "pretty", "plug", "far", "heartbreaking", "easy", "representative", "thing", "mountainous", "physical", "witty", "sidewalk", "obsequious", "scrape", "self", "tiny", "makeshift", "godly", "sail", "cautious", "value", "dress", "train", "division", "income", "birth"]



export const stateDefaults = {

  fileName: "default",
  loadTarget: "TF3_default",
  activeRegion: "tune-entry",
  previousRegion: '',
  //titles: true, // not in use yet, for displaying tutorial info as html titles when active?
  hideInfoMenu: false,
  sceneTitles: sceneTitles,

  fullRange:["C1","C#1","D1","D#1","E1","F1","F#1","G1","G#1","A1","B#1","B1","C2","C#2","D2","D#2","E2","F2","F#2","G2","G#2","A2","B#2","B2","C3","C#3","D3","D#3","E3","F3","F#3","G3","G#3","A3","A#3","B3","C4","C#4","D4","D#4","E4","F4","F#4","G4","G#4","A4","A#4","B4","C5","C#5","D5","D#5","E5","F5","F#5","G5","G#5","A5","A#5","B5","C6","C#6","D6","D#6","E6","F6","F#6","G6","G#6","A6","B#6","B6","C7","C#7","D7","D#7","E7","F7","F#7","G7","G#7","A7","B#7","B7","C8"],
  //noteKeys: [" ", "a", "z", "s", "x", "d", "c", "f", "v", "g", "b", "h", "n", "j", "m", ",", "l", ".", ";", "/", "'", "q", "2", "w", "3", "e", "r", "5", "t", "6", "y", "7", "u", "i", "9", "o", "0", "p", "-", "[", "=", "]", "Backspace", "\\"],
  //keyToPitch: {" ":" ", "z":"C3", "s":"C#3", "x":"D3", "d":"D#3", "c":"E3", "v":"F3", "g":"F#3", "b":"G3", "h":"G#3", "n":"A3", "j":"A#3", "m":"B3", ",":"C4", "l":"C#4", ".":"D4", ";":"D#4", "/":"E4", "'":"F4", "q":"C4", "2":"C#4", "w":"D4", "3":"D#4", "e":"E4", "r":"F4", "5":"F#4", "t":"G4", "6":"G#4", "y":"A4", "7":"A#4", "u":"B4", "i":"C5", "9":"C#5", "o":"D5", "0":"D#5", "p":"E5", "[":"F5", "=":"F#5", "]":"G5", "Backspace":"G#5", "\\":"A5" },
  noteKeys_RowsOctave: [" ", "z", "s", "x", "d", "c", "v", "g", "b", "h", "n", "j", "m", ",", "l", ".", ";", "/", "'", "q", "2", "w", "3", "e", "r", "5", "t", "6", "y", "7", "u", "i", "9", "o", "0", "p", "[", "=", "]", "Backspace", "\\"],
  noteKeys_Clusters: [" ", "z", "x", "c", "v", "a", "s", "d", "f", "q", "w", "e", "r", "1", "2", "3", "4", "m", ",", ".", "/", "j", "k", "l", ";", "'", "u", "i", "o", "p", "7", "8", "9", "0"],
  qwertyOctave: 3,
  keyToQwertyVal: {" ":" ", "z":"C-Lo", "s":"C#-Lo", "x":"D-Lo", "d":"D#-Lo", "c":"E-Lo", "v":"F-Lo", "g":"F#-Lo", "b":"G-Lo", "h":"G#-Lo", "n":"A-Lo", "j":"A#-Lo", "m":"B-Lo", ",":"C-Hi", "l":"C#-Hi", ".":"D-Hi", ";":"D#-Hi", "/":"E-Hi", "'":"F-Hi", "q":"C-Hi", "2":"C#-Hi", "w":"D-Hi", "3":"D#-Hi", "e":"E-Hi", "r":"F-Hi", "5":"F#-Hi", "t":"G-Hi", "6":"G#-Hi", "y":"A-Hi", "7":"A#-Hi", "u":"B-Hi", "i":"C-Hx", "9":"C#-Hx", "o":"D-Hx", "0":"D#-Hx", "p":"E-Hx", "[":"F-Hx", "=":"F#-Hx", "]":"G-Hx", "Backspace":"G#-Hx", "\\":"A-Hx" },
  keyToQwertyDisplay: 'Rows-Octave',
  keyToQwertyValRowsOctave: {" ":" ",
      "1":" ", "2":"C#-Hi", "3":"D#-Hi", "4":" ", "5":"F#-Hi", "6":"G#-Hi", "7":"A#-Hi", "8":" ", "9":"C#-Hx",  "0":"D#-Hx", "-":" ", "=":"F#-Hx", "Backspace":"G#-Hx",
      "q":"C-Hi", "w":"D-Hi",  "e":"E-Hi", "r":"F-Hi",  "t":"G-Hi", "y":"A-Hi", "u":"B-Hi", "i":"C-Hx", "o":"D-Hx", "p":"E-Hx", "[":"F-Hx",  "]":"G-Hx",  "\\":"A-Hx",
      "a":" ", "s":"C#-Lo", "d":"D#-Lo", "f":" ", "g":"F#-Lo",  "h":"G#-Lo", "j":"A#-Lo", "k":" ", "l":"C#-Hi", ";":"D#-Hi", "'":"F-Hi",
      "z":"C-Lo", "x":"D-Lo", "c":"E-Lo", "v":"F-Lo",  "b":"G-Lo", "n":"A-Lo", "m":"B-Lo", ",":"C-Hi",  ".":"D-Hi",  "/":"E-Hi",
  },
  keyToQwertyValClusters: { " ":" ",
      "1":"C-Hi", "2":"C#-Hi", "3":"D-Hi", "4":"D#-Hi",     "5":" ", "6":" ",      "7":"C-Hx", "8":"C#-Hx", "9":"D-Hx", "0":"D#-Hx",
      "q":"G#-Lo", "w":"A-Lo", "e":"A#-Lo", "r":"B-Lo",     "t":" ", "y":" ",      "u":"G#-Hi", "i":"A-Hi", "o":"A#-Hi", "p":"B-Hi",
      "a":"E-Lo", "s":"F-Lo", "d":"F#-Lo", "f":"G-Lo",      "g":" ", "h":" ",      "j":"E-Hi", "k":"F-Hi", "l":"F#-Hi", ";":"G-Hi",
      "z":"C-Lo", "x":"C#-Lo", "c":"D-Lo", "v":"D#-Lo",     "b":" ", "n":" ",      "m":"C-Hi", ",":"C#-Hi", ".":"D-Hi", "/":"D#-Hi",
  },

  playing: false,
  chain: false,
  chainLoop: false,
  editMode: 'overwrite',
  entrySound: true,

  endcap: {pitch:"_",random:'fixed'},

  playerParams:  {
    waveType: 'sawtooth',
    gain: 0.5,
    delayTime: 0,
    delayFeedback: 0,
    delayActive: true,
    distortion: 0,
    reverb: 0,
  },
  playerADSR: {
    attack: 0.005,
    decay: 0.1,
    sustain: 0.3,
    release: 3,
  },
  playerFilter: {
    filterWet: 0.8,
    filterType: 'lowpass',
    filterRolloff: -12,
    filterBaseFrequency: 200,
    filterQ: 0,
    LFOWaveType: 'sine',
    LFOFrequency: 0.5,
    LFODepth: 0.2,
    LFOOctaves: 2.6,
  },

  editingSceneNumber: 0, // currently lacks a mutation to change this
  editingSceneId: '',
  advanceTriggered: false,
  sceneChangeNumber: 0,

  newSceneDefaults: {
    title: '',
    id: '',
    bpm: 100,
    selectedNotes: ["C", "D", "E", "F", "G", "A", "B"],
    selectedLength: 8,
    tracks: [],
    editingTrackNumber: 0,
    editingTrackId: '',
    editingIndex: 0,
    leadTrackId: '',
    started: false,
    leadCycles: 0,
    suspendChanges: false,
    chainAdvancePer: 4,
    filterPitchesOnChange: true,
    modulatePerLeadChanges: 1,
    modulationCycles: 0,
    selectedRootPitches: ['C','G','D','A','E','B','Fs','Cs','Gs','Ds','As','F'],
    modulationWeights: {
      dia: 1, mel: 0, har: 0, dim: 0, aug: 0, chr: 0,
      maj: 0, min: 0, sus: 0, ma7: 0, dom: 0, mi7: 0,
      hdm: 0, dm7: 0, blu: 0, pen: 0, fth: 0, one: 0,
    },
    lastMode: 'C-dia',
    autoModulate: false,
    modulationStyle: 'drift',
    nextModulation: { modeBase: '', modePitches: [], modulation: '' }, // see note in autoModulate action
    editingForm: false,
    harmonicForm: [],
    formStep: -1,
    // any other form tracking variables?
  },

  scenes: [],
  sceneBench: [],

  newTrackDefaults: {
    rangeHigh: "C4",
    rangeLow: "C3",
    changeTotal: 0,
    changePer: 4,
    changePerRemembered: false,
    pitchPercent: 50,
    tune: [{pitch:"_",random:'fixed'}],
    rememberedTune: [],
    toneTuneIndex : 0,
    changeCycles: 0,
    id: '',
    lockNumber: 0,
    colorAlternation: 4,
    lineBreaks: [],
    hidePitches: false,
    soundPanel: true,
    waveType: 'sawtooth',
    gain: 0.5,
    muted: false,
    gainPreMute: '',
    portamento: 0,
    harmonicity: 1,
    modulationType: 'square',
    modulationIndex: 2,
    count: 2,
    spread: 20,
    modulationFrequency: 0.4,
    delayTime: 0,
    delayFeedback: 0,
    delayActive: true,
    distortion: 0,
    attack: 0.005,
    decay: 0,
    sustain: 1,
    noteDuration: '8n',  // UI display between attack and release, but has it's own mutation
    release: 1,
    filterWet: 0.5,
    filterType: 'lowpass',
    filterRolloff: -12,
    filterBaseFrequency: 200,
    filterQ: 0,
    LFOWaveType: 'sine',
    LFOFrequency: 0,
    LFODepth: 0,
    LFOOctaves: 3,
  },

}
